service: bubble-rewards-storefront-api
app: bubble-rewards-storefront-api
tenant: ahmeddauda

frameworkVersion: ">=1.28.0 <2.0.0"

provider:
  name: aws
  runtime: go1.x
  profile: serverless-agent-ahmed-aws-dev

functions:
  hello:
    handler: bin/hello
    events:
      - http:
          path: hello
          method: get
  world:
    handler: bin/world
    events:
      - http:
          path: world
          method: get

package:
 exclude:
   - ./**
 include:
   - ./bin/**
