service: bubble-rewards-storefront-api
app: bubble-rewards-storefront-api
tenant: ahmeddauda
credentials: ${file(./creds.yml)}

frameworkVersion: ">=1.28.0 <2.0.0"

provider:
  name: aws
  runtime: go1.x
  profile: serverless-agent-ahmed-aws-dev
  environment:
    DB_HOST: ${self:credentials.DB_HOST}
    DB_USER: ${self:credentials.DB_USER}
    DB_PASSWORD: ${self:credentials.DB_PASSWORD}
    DB_NAME: ${self:credentials.DB_NAME}

functions:
  validateCode:
    handler: bin/validateCode
    events:
      - http:
          path: validate/code
          method: get
          request:
            parameters:
              querystrings:
                code: true
                redemption_type: true
                key: true
package:
 exclude:
   - ./**
 include:
   - ./bin/**
